### ISSUE TITLE
New Logo/Graphic Needed

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/NorthWalesTech.github.io#1]
Anyone good at drawing?

> @carwyn 
> We need a better logo/graphic. It should have cogs in it! Or maybe a robot arm like https://wiki.gnome.org/Apps/Builder

**Comment by carwyn** [comment]
Inspiration: Google Image search the following (independently): North Wales, Technology

Maybe it should feature slate?

**Comment by carwyn** [comment]
We have a graphic designer at work, I'll see if I can get him to help with a logo.

**Comment by robshep** [comment]
Square ratio please.   Best for social media badges and icons :)

**Comment by carwyn** [comment]
Moved to: https://github.com/NorthWalesTech/NorthWalesTech/issues/5
